# Trigger for each pipeline is defined in the Devops portal
# so that the YAML remains agnostic
trigger: none

name: Core-Governance Deploy

variables:
  - group: Shared
  - name: workingDirectory
    value: $(System.DefaultWorkingDirectory)/$(Build.DefinitionName)
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - name: componentname
    value: $(Build.DefinitionName)

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CoreGovernanceWhatifAndDeploy

    jobs:
      - job: ValidateandWhatif

        steps:
          - task: AzureCLI@2
            displayName: Lint
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: $(WorkingDirectory)
              inlineScript: |
                az --version
                az bicep install
                bicep build $(componentname).bicep

          - task: AzurePowerShell@5
            displayName: What-If
            inputs:
              azureSubscription: $(azureServiceConnection)
              azurePowerShellVersion: LatestVersion
              pwsh: true
              workingDirectory: $(WorkingDirectory)
              ScriptType: "FilePath"
              ScriptPath: "./.azure-pipelines/CoreGovernanceTenantDeploy.ps1"
              scriptArguments:
                -whatif

      - job: Deploy
        dependsOn: ValidateandWhatif
        condition: and(succeeded(), eq(variables.isMain, 'true'))

        steps:
          - task: AzurePowerShell@5
            displayName: Deployment
            inputs:
              azureSubscription: $(azureServiceConnection)
              azurePowerShellVersion: LatestVersion
              pwsh: true
              workingDirectory: $(WorkingDirectory)
              ScriptType: "FilePath"
              ScriptPath: "./.azure-pipelines/CoreGovernanceTenantDeploy.ps1"
