# This workflow will deploy a Bicep file to Azure using GitHub Actions
name: Deploy Bicep
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev01" ]
  pull_request:
    branches: [ "dev01" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  # This job will install Bicep CLI and run the deployment
  deploy:
    # Run this job on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
      
      # Install Bicep CLI
      - name: Install Bicep CLI
        uses: azure/setup-bicep@v1
      
      # Login to Azure using service principal credentials
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Deploy the Bicep file to the resource group
      - name: Deploy Bicep file
        run: |
          az deployment group create \
            --resource-group ${{ secrets.AZURE_RG }} \
            --template-file "./StorageAccount/StorageAccount.bicep"